### PR TITLE
Install phing via composer

### PR DESCRIPTION
**Pull request by christianlupus**
Phing is recommended to be installed using composer. See https://www.phing.info/#install.

### CODE REVIEW

**Comment by dromer** [comment]
What do we use phing for?

**Comment by christianlupus** [comment]
According to https://wiki.partkeepr.org/wiki/Running_PartKeepr_from_GIT#Console_commands phing is used for automatically setup during development. Since some time (I did not research here) it is recommended to install phing via composer instead via system installation.

**Comment by dromer** [comment]
But, should it be installed always by default?

**Comment by christianlupus** [comment]
It is only on the dev bundle. So the production bundle will not be affected. 

In my docker images I put it into the entry point script. So, there I would need it anyways or install manually. Here I saw a possibility to make a small pr with clear functionality.

**Comment by dromer** [comment]
Ah right, I haven't worked with composer in a long time. Seems good then, so will merge :)

**Pull request merged**
