### PR TITLE
Removed travis build warnings

### PR DESCRIPTION
**Pull request by christianlupus**
There are some issues in the Travis config validation. These changes are merely cosmetic.

Additionally, the secret token of code_climate should be protected from the public view.

### CODE REVIEW

**Comment by dromer** [comment]
Lets have a look at the code-climate settings. I'm not familiar with them exactly. How the service works or accounts are accessed.
(this most likely is @Drachenkaetzchen 's personal account)

**Comment by dromer** [comment]
I'm looking at adding codecov support right now.

**Comment by christianlupus** [comment]
An alternative would maybe be the html code coverage report from phpunit itself. This would not involve any 3rd party service that could change their pricing and force us to reevaluate But for sure it is less fancy ;).

**Comment by dromer** [comment]
So, I'm not sure why the ```s/matrix/jobs/``` is that newer syntax?

**Comment by christianlupus** [comment]
According to https://config.travis-ci.com/ `jobs` is the correct syntax and `matrix` just an alias.
See also https://travis-ci.org/partkeepr/PartKeepr/builds/654121922/config. There are 2 issues regarding the travis syntax reported:
Screenshot_20200223_225220

**Comment by dromer** [comment]
Ah check. Good to know. Merging!

**Pull request merged**
