### PR TITLE
Add docker files to generate a development environment

### PR DESCRIPTION
**Pull request by christianlupus**
This PR should bring support for #1071.

As there are credentials needed, the main archive needs to be set up accordingly before the PR should be merged. Further details can be discussed if the main PR can be approved.

### CODE REVIEW

**Comment by dromer** [comment]
I had a quick look at your docker setup this weekend, but need time to test it.
So far it seems a bit overly complex though. Personally I would probably go somewhat of a different route for this, but then again I don't know what caveats come out of this.

Hope to do some testing (and maybe try some things from scratch) on my end to get a better insight into how this would be used.

**Comment by christianlupus** [comment]
I am sorry, I did not (yet) write any documentation on it. Maybe I start with some rough sketches how things are intended/working. This is the next thing on my agenda.

**Comment by christianlupus** [comment]
Just rebased onto latest master

**Comment by christianlupus** [comment]
@dromer I just joined the IRC chat room partkeepr on freenode. It might be simpler for us, if we needed to discuss details in a dialog than the chat system here. My username should be clupus there....

**Comment by dromer** [comment]
```12:41.37 [FreeNode] -!- There is no such nick clupus```

**Comment by christianlupus** [comment]
I just saw that the most recent changes break the development image when merged. Need to fix.

**Comment by christianlupus** [comment]
Was mislead, it should be working in the development image. The production image is still pending due to the required implementation of the code synchronization.

**Comment by christianlupus** [comment]
I just pushed the latest docker images to the docker hub. You might want to use them as cache for building.

**Comment by christianlupus** [comment]
@dromer I reconsidered the discussion about apache vs nginx and the corresponding issues on PHP and docker. Why do we need to use nginx and PHP-FPM? This opens a can of worms and makes the whole docker development much more involved.

Please keep in mind, I am not talking about production usage. We are talking about development where the traffic is low, the number of users are at most one typically and the goal is to have something running quickly.

I confirm, that the production environment should be indenpendant of the HTTP server used and the FPM poses multi-core benefits as well as some simplifications regarding reverse proxying for nginx. No arguing there. I might be able to build dedicated docker images for these cases later as well.

But for now I see the synchronization issue between the PHP-FPM and the HTTP (be it apache or nginx) might be much more involved than a simple runnning container "all in one". That way the developer needs less knowledge about the debugging structure than when two containers need to stay in sync (or a volume and a host folder).

**Comment by dromer** [comment]
Ok, I've been looking at this some more (sorry I haven't been getting emails lately. not sure what's up)

And considering all the example docker setups out there now:
* https://github.com/mhubig/docker-partkeepr
* https://github.com/bluelotussoftware/partkeepr
* https://github.com/kiall/docker-partkeepr

Lets learn from all of this to at least get the ball rolling!

If you can take the lead on this I'll be ready to help test your instructions, ok?

**Comment by dromer** [comment]
@christianlupus 

Can you move this effort to a branch on this repo?
Maybe after some cleanup/consolidation of the work?

**Comment by christianlupus** [comment]
OK, @ericmoon, I consolidated the docker setup a bit. I did not move to a branch on that repo because I think there is no way to change the PR's sources.
For now, there is a GH actions prepared to push the images to docker hub. This will fail currently as the secrets are not (yet) set up accordingly. If you have any questions, feel free to ask.

**Comment by ericmoon** [comment]
First glance looks good.  I'll try and give a load and test in the next few days.

**Comment by ericmoon** [comment]
Took more than a few days (sorry), but it works great!  Instructions are very good

(minor fix: remove the leading "." from the github.env files in the directions.)

**Comment by ericmoon** [comment]
I was able to run unit tests inside of the dev docker container.  2 tests were skipped, so it's not perfect, but it seems to be working well.

**Pull request merged**
