### PR TITLE
typo for github.env

### PR DESCRIPTION
**Pull request by ericmoon**
not sure if you meant to use dot file for github.env, but now the README matches the code. (everything is non-dot files)

### CODE REVIEW

**Comment by christianlupus** [comment]
You are right. Thanks for the hint.

**Comment by ericmoon** [comment]
looks like a few other things got pulled in with this too that i didn't necessarily intend yet.    should be fine, but I'll be more careful in the future. sorry 'bout that.

**Comment by christianlupus** [comment]
@ericmoon To keep things clean, should we revert the PR  and you create a new PR with only the relevant parts (aka not the dependencies) in? Then we can put the dependency updates into their own branch(es).

**Comment by ericmoon** [comment]
@christianlupus Yes, that makes the most sense.  I'll do another one without the deps.  I think we can keep the travis yaml with the composer workaround until we get github actions working well, then dump travis.

**Pull request merged**
