### PR TITLE
Added requirements for PHP<7.2 and FreeType extension

### PR DESCRIPTION
**Pull request by christianlupus**
This PR should add additional checks in the setup.

Related to #905 and some bug I found during work for #1088.

Needs checking before it can be merged.

### CODE REVIEW

**Comment by christianlupus** [comment]
This gets more important see #1102 and #1110.

**Comment by christianlupus** [comment]
I am surprised that StyleCI was insisting on bad formatting in parts I did not modify. The last commit in this PR/branch might be reduced if only the modified files were to change....

**Comment by dromer** [comment]
Heh, interesting @ styleci trigger. Lets merge!

**Comment by dromer** [comment]
I've now made styleci automatically create a PR with fixes. This means that we can more easily merge this pesky business ;)
(I'm really considering moving away from styleci when we have a reliable build-env going that includes local style tester that can be integrated into travis builds)

**Comment by christianlupus** [comment]
See #1092 and #1093 for cross reference.

**Comment by dromer** [comment]
I think it will be nice if the travis builds fail early with the style. that means we don't have to wait endlessly when we know the full pipeline doesn't work ;)

(at work we do this with python/tox: first run flake8, when it fails ignore the rest)

**Pull request merged**
