### PR TITLE
Tidied up travis file a bit

### PR DESCRIPTION
**Pull request by christianlupus**
The travis file has some old references to hhvm that clobber the file. I removed them for simpler readability.

### CODE REVIEW

**Comment by dromer** [comment]
What do you mean clobber? Isn't hhvm used in the build then?

**Comment by christianlupus** [comment]
I do not see it used anywhere. At least not in Travis. Also there is no column entry `hhvm` in the test matrix. It might be a reminder from older tests but in the current file it does not make sense to me.

**Comment by christianlupus** [comment]
I just looked into the history. [This commit](https://github.com/partkeepr/PartKeepr/commit/18cd05c251e31cb9dae8871cc882fd1e72299c56#diff-354f30a63fb0907d4ad57269548329e3) removed `hhvm` from the Travis script.

**Comment by dromer** [comment]
Indeed. Lets clean it up.

**Pull request merged**
